local u = require('Utf8String')

assert( u'фыва' == u'фыва' )
assert( u._fromtable{'ф','ы','в','а'} == u'фыва' )
assert( tostring( u'фыва' ) == 'фыва' )
assert( u.char( 1092, 1099, 1074, 1072 ) == u'фыва' )
assert( u'фыва':sub(1,2) == u'фы' )
assert( u'фыва':sub(-3,-1) == u'ыва' )
assert( byte('фыва') == 1092 )
assert( byte('фыва',2) == 1099 )
local a, b, c, d = byte( 'фыва', 1, -1 )
assert( a == 1092 and b == 1099 and c == 1074 and d == 1072 )
assert( #u'фыва' == 4 )
assert( u'фыва':len() == 4 )
assert( u'фыва':reverse() == u'авыф' )
assert( u'фыва':rep( 3 ) == u'фывафывафыва' )
